apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: listingapi
  creationTimestamp: null
  labels:
    app: listingapi
spec:
  selector:
    matchLabels:
      app: listingapi
  replicas: 3 # Number of replicas that will be created for this deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: listingapi
    spec:
      containers:
        - name: llistingapi
          image: devsahamerlin/listingrestapi # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081 # The port that the container is running on in the cluster
          resources: {}

status: {}
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: lb-listingapi-service
  labels:
    app: lb-listingapi-service
spec:
  type: LaodBalancer
  selector:
    app: listingapi
  ports:
    - protocol: "TCP"
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
  type: NodePort # type of the service.